### ISSUE TITLE
Lectura y escritura de contratos inteligentes 

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/practica-4y5-remi#1]
[Práctica de lectura y escritura de contratos inteligentes.pdf](https://github.com/SistemasTecTlaxiaco/practica-4y5-remi/files/8642186/Practica.de.lectura.y.escritura.de.contratos.inteligentes.pdf)

**Comment by carlos-chrs** [comment]
Portada: 25 puntos.
Procedimiento: 25 puntos.
Figuras, ilustraciones y fotografías: 25 puntos.
Resultados y conclusiones: 25 puntos.
Total: 100 puntos = Calificación: 20/20.

Muy Bien Echo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
